variables:
  GOBO: '$CI_PROJECT_DIR'

#
# Build Gobo tools.
#

build_ge:
  stage: build_ge
  dependencies: []
  script:
    - Write-Host "Just to define the 'build_ge' stage name"
  rules:
    - when: never

linux_gcc_build_ge:
  stage: build_ge
  tags:
    - linux
  image:
# See: https://stackoverflow.com/questions/44319313/how-do-i-use-powershell-with-gitlab-ci-in-gitlab-pages
    name: "mcr.microsoft.com/powershell:latest"
  dependencies: []
  script:
    - pwsh -f "$GOBO/.cicd/build_ge.ps1" gitlab gcc
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null || $GOBO_CUSTOM_PIPELINE == "linux_test_ise"
      when: on_success
  artifacts:
    when: always
    expire_in: 3 hours
    paths:
      - $GOBO/bin/
      - $GOBO/tool/gec/backend/c/config/default.cfg

windows_msc_build_ge:
  stage: build_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies: []
  script:
    - . "$GOBO/.cicd/build_ge.ps1" gitlab msc
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null || $GOBO_CUSTOM_PIPELINE == "windows_test_ise"
      when: on_success
  artifacts:
    when: always
    expire_in: 3 hours
    paths:
      - $GOBO/bin/
      - $GOBO/tool/gec/backend/c/config/default.cfg

#
# Running tests with Gobo Eiffel.
#

test_ge:
  stage: test_ge
  dependencies: []
  script:
    - Write-Host "Just to define the 'test_ge' stage name"
  rules:
    - when: never

library_linux_gcc_test_ge:
  stage: test_ge
  tags:
    - linux
  image:
# See: https://stackoverflow.com/questions/44319313/how-do-i-use-powershell-with-gitlab-ci-in-gitlab-pages
    name: "mcr.microsoft.com/powershell:latest"
  dependencies:
    - linux_gcc_build_ge
  script:
    - pwsh -f "$GOBO/.cicd/test_ge.ps1" gitlab gcc ge library
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

tool_linux_gcc_test_ge:
  stage: test_ge
  tags:
    - linux
  image:
# See: https://stackoverflow.com/questions/44319313/how-do-i-use-powershell-with-gitlab-ci-in-gitlab-pages
    name: "mcr.microsoft.com/powershell:latest"
  dependencies:
    - linux_gcc_build_ge
  script:
    - pwsh -f "$GOBO/.cicd/test_ge.ps1" gitlab gcc ge tool
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

library_windows_msc_test_ge:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - windows_msc_build_ge
  script:
# The tests in `$GOBO\library\lexical` are failing in GitLab CI/CD when using `geant test_ge`.
# So use `geant test_debug_ge` instead.
    - . "$GOBO/.cicd/test_ge.ps1" gitlab msc debug_ge library
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

# We have `tool_no_gec_windows_msc_test_ge` and `tool_gec_windows_msc_test_ge`,
# instead of just `tool_windows_msc_test_ge`, because it takes more than
# 1 hour to run this job and the job timeout on GitLab runners for Windows 
# is set to 1 hour (even though it is set to 2 hours for the project).

tool_no_gec_windows_test_ge:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - windows_msc_build_ge
  script:
    - Remove-Item "$GOBO/tool/gec/test" -Force -Recurse
    - . "$GOBO/.cicd/test_ge.ps1" gitlab msc ge tool
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

tool_gec_windows_msc_test_ge:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - windows_msc_build_ge
  script:
    - . "$GOBO/.cicd/test_ge.ps1" gitlab msc ge tool/gec
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

#
# Running tests with ISE Eiffel.
#

library_linux_gcc_test_ise:
  stage: test_ge
  tags:
    - linux
  image:
# See: https://stackoverflow.com/questions/44319313/how-do-i-use-powershell-with-gitlab-ci-in-gitlab-pages
    name: "mcr.microsoft.com/powershell:latest"
  dependencies:
    - linux_gcc_build_ge
  script:
    - pwsh -f "$GOBO/.cicd/test_ge.ps1" gitlab gcc debug_ise library
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == "linux_gcc_test_ise"
      when: on_success
  timeout: 3 hours

tool_linux_gcc_test_ise:
  stage: test_ge
  tags:
    - linux
  image:
# See: https://stackoverflow.com/questions/44319313/how-do-i-use-powershell-with-gitlab-ci-in-gitlab-pages
    name: "mcr.microsoft.com/powershell:latest"
  dependencies:
    - linux_gcc_build_ge
  script:
    - pwsh -f "$GOBO/.cicd/test_ge.ps1" gitlab gcc debug_ise tool
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == "linux_gcc_test_ise"
      when: on_success
  timeout: 3 hours

# We have `library_no_xslt_windows_msc_test_ise` and `library_xslt_msc_windows_test_ise`,
# instead of just `library_windows_msc_test_ise`, because it takes more than
# 1 hour to run this job and the job timeout on GitLab runners for Windows 
# is set to 1 hour (even though it is set to 2 hours for the project).

library_no_xslt_windows_msc_test_ise:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - windows_msc_build_ge
  script:
    - Remove-Item "$GOBO/library/xslt/test" -Force -Recurse
# Use ISE Eiffel in finalized mode because it takes more than
# 1 hour to run this job in workbench mode and the job timeout
# on GitLab runners for Windows is set to 1 hour (even though
# it is set to 2 hours for the project).
    - . "$GOBO/.cicd/test_ge.ps1" gitlab msc ise library
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == "windows_msc_test_ise"
      when: on_success

library_xslt_windows_msc_test_ise:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - windows_msc_build_ge
  script:
# Use ISE Eiffel in finalized mode because it takes more than
# 1 hour to run this job in workbench mode and the job timeout
# on GitLab runners for Windows is set to 1 hour (even though
# it is set to 2 hours for the project).
    - . "$GOBO/.cicd/test_ge.ps1" gitlab msc ise library/xslt
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == "windows_msc_test_ise"
      when: on_success

tool_windows_msc_test_ise:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  dependencies:
    - windows_msc_build_ge
  script:
    - . "$GOBO/.cicd/test_ge.ps1" gitlab msc debug_ise tool
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == "windows_msc_test_ise"
      when: on_success

#
# Stages.
#

stages:
  - build_ge
  - test_ge
