#
# Running tests.
#

parameters:
  - name: os
    type: string
    default: ''
  - name: c_compiler
    type: string
    default: ''
  - name: vm_image
    type: string
    default: ''

stages:
  - stage: ${{ parameters.os }}_${{ parameters.c_compiler }}_test
    dependsOn: ${{ parameters.os }}_${{ parameters.c_compiler }}_build
    jobs:
      - job: ${{ parameters.os }}_${{ parameters.c_compiler }}_test
        pool:
          vmImage: ${{ parameters.vm_image }}
        timeoutInMinutes: 180
        strategy:
          matrix:
            ge_library:
              GOBO_CI_EIFFEL_COMPILER: ge
              GOBO_CI_SYSTEM_UNDER_TEST: library
            ge_tool:
              GOBO_CI_EIFFEL_COMPILER: ge
              GOBO_CI_SYSTEM_UNDER_TEST: tool
            debug_ge_library:
              GOBO_CI_EIFFEL_COMPILER: debug_ge
              GOBO_CI_SYSTEM_UNDER_TEST: library
            debug_ge_tool:
              GOBO_CI_EIFFEL_COMPILER: debug_ge
              GOBO_CI_SYSTEM_UNDER_TEST: tool
            ise_library:
              GOBO_CI_EIFFEL_COMPILER: ise
              GOBO_CI_SYSTEM_UNDER_TEST: library
            ise_tool:
              GOBO_CI_EIFFEL_COMPILER: ise
              GOBO_CI_SYSTEM_UNDER_TEST: tool
            debug_ise_library:
              GOBO_CI_EIFFEL_COMPILER: debug_ise
              GOBO_CI_SYSTEM_UNDER_TEST: library
            debug_ise_tool:
              GOBO_CI_EIFFEL_COMPILER: debug_ise
              GOBO_CI_SYSTEM_UNDER_TEST: tool
        steps:
          - download: current
            artifact: gobo_bin_${{ parameters.os }}_${{ parameters.c_compiler }}
          - pwsh: Move-Item -Path "$(Pipeline.Workspace)/gobo_bin_${{ parameters.os }}_${{ parameters.c_compiler }}/*" -Destination "$(Build.Repository.LocalPath)/bin" -Force
          - download: current
            artifact: gobo_c_config_${{ parameters.os }}_${{ parameters.c_compiler }}
          - pwsh: Move-Item -Path "$(Pipeline.Workspace)/gobo_c_config_${{ parameters.os }}_${{ parameters.c_compiler }}/*" -Destination "$(Build.Repository.LocalPath)/tool/gec/backend/c/config" -Force
          - pwsh: . "$(Build.Repository.LocalPath)/.cicd/test_ge.ps1" azure ${{ parameters.c_compiler }} $env:GOBO_CI_EIFFEL_COMPILER $env:GOBO_CI_SYSTEM_UNDER_TEST
            name: test
