name: "GitHub Actions"

on:
  push:
    branches:
      - '*'
      - '*/**'
    tags-ignore:
      - '*'
  pull_request:

jobs:

#
# Build Gobo tools.
#

  linux_build:
    if: ${{ github.repository == 'ebezault/gobo' || github.repository == 'gobo-eiffel/gobo' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [zig, gcc]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: . "$env:GITHUB_WORKSPACE/.cicd/build_ge.ps1" github ${{ matrix.c_compiler }}
        shell: pwsh
        env:
          GE_NO_DEFAULT_BOEHM_GC: true
      - uses: actions/upload-artifact@v4
        with:
          name: gobo_bin_linux_${{ matrix.c_compiler }}
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: gobo_c_config_linux_${{ matrix.c_compiler }}
          path: tool/gec/backend/c/config/default.cfg
          retention-days: 1

  macos_build:
    if: ${{ github.repository == 'ebezault/gobo' || github.repository == 'gobo-eiffel/gobo' }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [zig, clang]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: . "$env:GITHUB_WORKSPACE/.cicd/build_ge.ps1" github ${{ matrix.c_compiler }}
        shell: pwsh
        env:
          GE_NO_DEFAULT_BOEHM_GC: true
      - uses: actions/upload-artifact@v4
        with:
          name: gobo_bin_macos_${{ matrix.c_compiler }}
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: gobo_c_config_macos_${{ matrix.c_compiler }}
          path: tool/gec/backend/c/config/default.cfg
          retention-days: 1

  windows_build:
    if: ${{ github.repository == 'ebezault/gobo' || github.repository == 'gobo-eiffel/gobo' }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [zig, msc]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: . "$env:GITHUB_WORKSPACE/.cicd/build_ge.ps1" github ${{ matrix.c_compiler }}
        env:
          GE_NO_DEFAULT_BOEHM_GC: true
      - uses: actions/upload-artifact@v4
        with:
          name: gobo_bin_windows_${{ matrix.c_compiler }}
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: gobo_c_config_windows_${{ matrix.c_compiler }}
          path: tool/gec/backend/c/config/default.cfg
          retention-days: 1

#
# Run tests.
#
  
  linux_test:
    runs-on: ubuntu-latest
    needs: linux_build
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [zig, gcc]
        eiffel_compiler: [ge, debug_ge, ise, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: gobo_bin_linux_${{ matrix.c_compiler }}
          path: bin
      - uses: actions/download-artifact@v4
        with:
          name: gobo_c_config_linux_${{ matrix.c_compiler }}
          path: tool/gec/backend/c/config
      - name: test
        run: . "$env:GITHUB_WORKSPACE/.cicd/test_ge.ps1" github ${{ matrix.c_compiler }} ${{ matrix.eiffel_compiler }} ${{ matrix.system_under_test }}
        shell: pwsh
        env:
          GE_NO_DEFAULT_BOEHM_GC: true

  macos_test:
    runs-on: macos-latest
    needs: macos_build
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [zig, clang]
        eiffel_compiler: [ge, debug_ge, ise, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: gobo_bin_macos_${{ matrix.c_compiler }}
          path: bin
      - uses: actions/download-artifact@v4
        with:
          name: gobo_c_config_macos_${{ matrix.c_compiler }}
          path: tool/gec/backend/c/config
      - name: test
        run: . "$env:GITHUB_WORKSPACE/.cicd/test_ge.ps1" github ${{ matrix.c_compiler }} ${{ matrix.eiffel_compiler }} ${{ matrix.system_under_test }}
        shell: pwsh
        env:
          GE_NO_DEFAULT_BOEHM_GC: true

  windows_test:
    runs-on: windows-latest
    needs: windows_build
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [zig, msc]
        eiffel_compiler: [ge, debug_ge, ise, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: gobo_bin_windows_${{ matrix.c_compiler }}
          path: bin
      - uses: actions/download-artifact@v4
        with:
          name: gobo_c_config_windows_${{ matrix.c_compiler }}
          path: tool/gec/backend/c/config
      - name: test
        run: . "$env:GITHUB_WORKSPACE/.cicd/test_ge.ps1" github ${{ matrix.c_compiler }} ${{ matrix.eiffel_compiler }} ${{ matrix.system_under_test }}
        env:
          GE_NO_DEFAULT_BOEHM_GC: true
